baseurl: "https://lextalk.tech/"
title: "LexTalk Tech"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "LexTalk - Tech"
  Description: "A quarterly technology conference held in Lexington KY"
  Date: "Oct 12th 2023"
  Venue: "The Cornerstone"
  VenueURL: "https://cornerstone.uky.edu/"
  Address: "401 S Limestone"
  City:  "Lexington"
  State: "KY"
  Images: ["/img/background.png"]
  # GoogleMapsKey: "AIzaSyAR3-wrHdxAS5P8ESI8S_IssOCpuxlf_Co"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    # - location
    - schedule
    # - speakers
    # - sponsors
    # - partners
    # - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Get tickets now!"
    link: "https://www.eventbrite.com/e/716404403857?aff=oddtdtcreator"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  # ForkButton:
  #   repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "Hugo"
      logo: "/img/hugo.png"
      url: "http://gohugo.io"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "Check-in"
      time: "5:30pm"

    - name: "Joe Kratzat"
      photo: "/img/speaker.jpg"
      bio: "Just a guy who plays on computers."
      company: ""
      link:
        href: "http://twitter.com/"
        text: "@Lorem"
      presentation:
        title: "LexTalk.Tech Intro"
        description: "This will be a welcome and introduction to what LexTalk Tech is and what we hope to bring to the community."
        time: "6:00"

    - name: "Todd Willey"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: ""
      link:
        href: "http://github.com/Lorem"
        text: "@Lorem"
      presentation:
        title: "Ham Radio: Where Even Experts are Amateurs"
        description: "A brief introduction into the Amateur Radio Service and how hams operate."
        time: "6:15pm"

    - name: "Davis St. Aubin"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: ""
      link:
        href: "http://twitter.com/Lorem"
        text: "@Lorem"
      presentation:
        title: "Things I hate about developers"
        description: ""
        time: "6:30pm"

    - name: "Craig Geil"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: ""
      link:
        href: "http://github.com/stevie"
        text: "@stevie"
      presentation:
        title: "Introduction to Vue.js"
        description: ""
        time: "6:45pm"

    - name: "John Martinez"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: ""
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
      presentation:
        title: "ASM R you serious"
        description: ""
        time: "7:00pm"

    - name: "Lee Park"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: ""
      link:
        href: "http://twitter.com/woz"
        text: "@woz"
      presentation:
        title: "LLMs throughout the lifecycle of Generative AI Projects"
        description: "Focused more on demystifying some keywords people vaguely understand about customizing language models for specific use cases."
        time: "7:30pm"

    - name: "Wrap up"
      time: "8:00pm"
    
    - name: "Pizza and beer afterward"
      presentation:
        description: "Within Cornerstone there is Ethereal brewing and Rolling oven Pizza."
        time: "8:00pm - 10pm"